POST http://localhost:3000/login HTTP/1.1
content-type: application/json

{
    "email": "test",
    "password": "test"
}

###

POST http://localhost:3000/login HTTP/1.1
content-type: application/json

{
    "email": "gebruiker2@hotmail.com",
    "password": "W@chtwoord2"
}

###

GET http://localhost:3000/gebruikers HTTP/1.1
Content-Type: application/json

###

GET http://localhost:3000/emails/gebruiker6@hotmail.com HTTP/1.1
Content-Type: application/json

###

GET http://localhost:3000/emails/test HTTP/1.1
Content-Type: application/json

